name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-release:
    name: "Pre-Release"
    runs-on: ubuntu-latest

    steps:
      - name: "prepare-sqlx"
        run: cargo install sqlx-cli
      - name: "prepare-database"
        run: sqlx database create --database-url=sqlite:data.db && sqlx migrate run --database-url=sqlite:data.db --source=migrations/
      - name: "Build & test"
        run: cargo build --release --verbose
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/release/api-server
            data.db
            .env
