name: Auto release/check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-mac-build:
    runs-on: macos-latest

    steps:
      # mac support
      - name: Compile for Mac
        id: Mac
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: aarch64-apple-darwin
          UPLOAD_MODE: none
          EXTRA_FILES: ".env data.db"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.Mac.outputs.BUILT_ARCHIVE }}
            ${{ steps.Mac.outputs.BUILT_CHECKSUM }}

  create-development-build:
    runs-on: ubuntu-latest
    needs: create-mac-build

    steps:
      - uses: actions/checkout@master

      - name: Set up data.db
        run: |
          cargo install sqlx-cli
          sqlx database create
          sqlx migrate run
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      
      # windows support
      - name: Compile for Windows
        id: Windows
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
          EXTRA_FILES: 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.Windows.outputs.BUILT_ARCHIVE }}
            ${{ steps.Windows.outputs.BUILT_CHECKSUM }}
      
      # linux support
      - name: Compile for Linux
        id: Linux
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          EXTRA_FILES: ".env data.db"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.Linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.Linux.outputs.BUILT_CHECKSUM }}
      
      # final release
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ steps.Windows.outputs.BUILT_ARCHIVE }}
            ${{ steps.Windows.outputs.BUILT_CHECKSUM }}
            ${{ steps.Linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.Linux.outputs.BUILT_CHECKSUM }}
            ${{ steps.Mac.outputs.BUILT_ARCHIVE }}
            ${{ steps.Mac.outputs.BUILT_CHECKSUM }}